### ISSUE TITLE
This is a sample issue.

### ISSUE THREAD

**Issue by mbhoude** [WHS-FRC-3467/Skip-5.5#3]
I have issues.  I'm just familiarizing myself with various aspects of this system.  This would be a good way for programmers to document various issues we encounter and want to notify each other.

**Comment by Starguy18** [comment]
What seems to be the issue?

The Doctor

On Tue, Feb 3, 2015 at 7:46 PM, Mike Houde notifications@github.com wrote:

> I have issues. I'm just familiarizing myself with various aspects of this
> system. This would be a good way for programmers to document various issues
> we encounter and want to notify each other.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WHS-FRC-3467/Skip-5.5/issues/3.

## 

This e-mail is intended solely for the person or entity to which it is 
addressed and may contain confidential and/or privileged information. Any 
review, dissemination, copying, printing, or other use of this e-mail by 
persons or entities other that the addressee is strictly prohibited. If you 
receive this e-mail in error, please notify the sender immediately and 
delete the material from any computer.

**Comment by mbhoude** [comment]
This is a catch-22 thing.  My issue is not really an issue.

**Comment by ehamwey** [comment]
Issue closed.
